[theme]
primaryColor = "#F47A38"               # Gulls orange
backgroundColor = "#000000"            # deep/dark background
secondaryBackgroundColor = "#041E42"   # Gulls navy
textColor = "#FFFFFF"                  # white text
font = "sans serif"
